name: mdb_copilot
description: MDB Copilot - Assistant Marchand de Bien
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  dio: ^5.7.0
  drift: ^2.22.1
  drift_flutter: ^0.2.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.3.1
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  sqlite3_flutter_libs: ^0.5.28
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.14
  drift_dev: ^2.22.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
